### ISSUE TITLE
Integrate simulator-core as an OMOTES worker & write the relevant timeseries to InfluxDB

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#14]

**Comment by MichielTukker** [comment]
Done: [ghcr.io/project-omotes/omotes-simulator-worker:0.0.4](https://github.com/Project-OMOTES/simulator-worker/pkgs/container/omotes-simulator-worker)

some todo's are still left open,  but no deal breakers for MVP? @lfse-slafleur

**Comment by lfse-slafleur** [comment]
Released as part of 'mvp' release of OMOTES
