### ISSUE TITLE
Typescript OMOTES SDK to integrate GeoSmartDesign Heat with OMOTES

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#15]

**Comment by WouterSpaak** [comment]
Tracked in this PR: https://github.com/Project-OMOTES/typescript-sdk/pull/3

**Comment by WouterSpaak** [comment]
Demo apps are working, which by extension means the SDK is working and ready to be consumed when that PR is merged.
