### ISSUE TITLE
use the ‘multiple profile-server’ functionality of MapEditor to store the credentials for the OMOTES influxdb instance so we do not have to embed the credentials in the ESDL

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#21]

**Comment by edwinmatthijssen** [comment]
Functionality is implemented, but not tested yet. Available on next release

**Comment by ewoudwerkman** [comment]
Is this ready to deploy on test env?

**Comment by edwinmatthijssen** [comment]
let's discuss in 3 minutes :-)

**Comment by lfse-slafleur** [comment]
@edwinmatthijssen  Will relay example of how to configure to Sebastiaan & Mark.

**Comment by lfse-slafleur** [comment]
@TNO-SlaFleur Release can be done with commit hash. (Main/master branch)

**Comment by edwinmatthijssen** [comment]
It was tested last Friday. Functionality works (after deleting the Grafana datasource)
