### ISSUE TITLE
Which opensource license to use

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#26]

**Comment by edwinmatthijssen** [comment]
FYI: ESDL, pyESDL, ESDL MapEdtior and everything else we've published all have the Apache 2.0 license. This was decided after discussion with our legal department.

**Comment by lfse-slafleur** [comment]
Settled on GPLv3 for OMOTES components, Apache 2.0 for SDK's and LGPLv3 for any other libraries.
