### ISSUE TITLE
MapEditor crashes when an ESDL is parsed that contains 'empty' KPIs

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#3]
Attached ESDL: 
[TEST2 with return network_GrowOptimized.txt](https://github.com/Nieuwe-Warmte-Nu/issues-and-project/files/12699283/TEST2.with.return.network_GrowOptimized.txt)

Sam found this bug if there are any further questions.

When a KPI is missing its values, MapEditor crashes when it loads the ESDL. Relevant part of ESDL:

```xml
        <KPIs xsi:type="esdl:KPIs" id="634db16c-d579-4a9b-a0e6-21e464d141a9">
          <kpi xsi:type="esdl:DoubleKPI" name="Investment">
            <quantityAndUnit xsi:type="esdl:QuantityAndUnitType" multiplier="MEGA" unit="EURO" physicalQuantity="COST"/>
          </kpi>
          <kpi xsi:type="esdl:DoubleKPI" name="Installation">
            <quantityAndUnit xsi:type="esdl:QuantityAndUnitType" multiplier="MEGA" unit="EURO" physicalQuantity="COST"/>
          </kpi>
        </KPIs>
```

**Comment by edwinmatthijssen** [comment]
Issue found and fixed in main branch

**Comment by jimrojerTNO** [comment]
@edwinmatthijssen @TNO-SlaFleur I just checked the esdl now is properly loaded, can we close this issue?
