### ISSUE TITLE
Names of workflows for frontends as read by the endusers.

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#32]
@martijnclarijs will discuss it with @samvanderzwan .

**Comment by martijnclarijs** [comment]
sent email Apr 16 2024 with new names of workflows for front end in MVP version of NWN DTK

**Comment by lfse-slafleur** [comment]
@lfse-slafleur  Notify stakeholders regarding relevant names

**Comment by lfse-slafleur** [comment]
omotes-rest is using the new names already. MapEditor environments still need to be updated. Mark is on it.

**Comment by lfse-slafleur** [comment]
Stakeholders are notified.

**Comment by lfse-slafleur** [comment]
Applied at both NWN-DTK & ESDL MapEditor frontends
