### ISSUE TITLE
Need a proper name for project/toolkit unrelated to NieuweWarmteNu

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#5]
Once this name is chosen, we need to update the Github organisation name as well as buy the relevant domain(s).

**Comment by lfse-slafleur** [comment]
As discussed with Martijn:

We need a name for the opensource part of our project. That will mainly be the backend. Any frontend is out-of-scope although we will reference MapEditor as the 'opensource' frontend which may be used for developers & R&D purposes.
Audience include users who want to deploy the backend and integrate in their own systems, users who want to try out the backend, software parties who want to build their own frontend & relevant opensource communities such as the pandapipes community.

For context: The quickstart for this project will use the 'nwn-sdk' which is what users & developers should integrate with which is a Python (& later Typescript) library.

We shall consider MapEditor as a separate project and consider it 'upstream' as we are integrated with MapEditor and therefore its users.

Considering the audience, it makes sense to keep it English. Words like 'thermal', 'models', 'calculation models', 'API', 'model suite' seem to fit and make sense.

**Comment by martijnclarijs** [comment]
Here is the name: Open Models Thermal Energy Systems (OMOTES)

(fyi, the related name for the key figures database will be: Database: Open Database Thermal Energy Systems (ODATES)

**Comment by lfse-slafleur** [comment]
@martijnclarijs  Thank you Martijn! I really like the name, I think it covers it well. Time to rename everything as soon as we can.

**Comment by lfse-slafleur** [comment]
New action is covered by #9
