### ISSUE TITLE
addusers for MapEditor needs to add e-mail addresses only in lowercase

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#7]
... as keycloak lowercases any e-mail addresses anyways.

This will prevent issues in the future where MapEditor configs cannot be found.

**Comment by edwinmat** [comment]
What's the issue exactly?  Or the proposed solution?   Do you propose to convert email addresses to lowercase before searching the user in our user database?

**Comment by lfse-slafleur** [comment]
Very specifically I propose to add '.lower()' to line `"email": row[1],` -> `"email": row[1].lower(),` in the file `add_users_csv.py` on line 28.

**Comment by edwinmatthijssen** [comment]
Done! Also added it to set_settings_csv.py to make sure, email address in MongoDB also becomes lower case. If I understand you correctly, Keycloak always lowercases email addresses, so I think making the change in add_users.csv is not even necessary.

**Comment by lfse-slafleur** [comment]
Cheers!
