### ISSUE TITLE
Rename organisation to new name OMOTES

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#9]
We have settled on the name 'Open Models Thermal Energy Systems (OMOTES)' for this project. We need to rename the Github organisation. As a consequence, developers will need to update their Github URL's as well as updating the Pypi trusted publishers.

**Comment by WouterSpaak** [comment]
FYI: I created an [@omotes](https://www.npmjs.com/org/omotes) organisation on NPM where we can publish javascript (typescript) packages and libraries.
